name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:10

      - name: Change stability to dev
        run: |
          cd ../app
          sed -i 's/"minimum-stability": "stable"/"minimum-stability": "dev"/' composer.json

      - name: Install Genesis
        run: |
          composer require devdojo/genesis dev-main
          php artisan ui genesis

      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
